### PR TITLE
Create MAP_loader.py

### PR DESCRIPTION
**Pull request by cbini**
Not sure of the your design patterns regarding configuration, but we use a relative import for the keys and database utility functions

### CODE REVIEW

**Comment by hunterowens** [comment]
I'll redo based on the eduextractor config. Thanks, @cbini

**Comment by hunterowens** [comment]
Hey @cbini 

Any idea on how to load historical data, as well? 

-Hunter

**Comment by almartin82** [comment]
so, not the best, but you have to request the old file, wait for NWEA to
provide it, then intake it whenever they provide it.  it's... a bummer.

**Comment by cbini** [comment]
Yeah, the quickest workaround in my head (without having to replicate all
of the JavaScript and cookies) would be a one-time selenium job that cycles
through previous terms, grabs the file when ready, and loads it

That could take a long time to run though.

**Pull request merged**
